name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:

  test-x86:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        arch: [ x86_64 ]
        python_version: [
          "3.10",
          "3.11"
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install
        run: |
          CMAKE_GENERATOR=Ninja pip install . -v

      - name: Build SwiftShader
        run: |
          git clone https://github.com/google/swiftshader.git && cd swiftshader/build
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          cmake .. && cmake --build . --parallel 4

      - name: Test
        run: |
          export VK_ICD_FILENAMES=$PWD/swiftshader/build/Linux/vk_swiftshader_icd.json
          pytest --ignore-glob=*test_nns* tests


#  test-aarch64:
#
#    runs-on: ubuntu-latest
#
#    strategy:
#      fail-fast: false
#      matrix:
#        base_image: [
#          "balenalib/raspberrypi4-64-ubuntu-python:3.10-jammy-build",
#          "balenalib/raspberrypi4-64-ubuntu-python:3.11-jammy-build"
#        ]
#
#    steps:
#      - name: Setup cache
#        uses: actions/cache@v2
#        with:
#          path: |
#            ~/.ccache
#          key: build_v1_${{ matrix.base_image }}
#
#      - uses: actions/checkout@v3
#      - uses: uraimo/run-on-arch-action@v2.5.0
#        name: Run commands
#        id: runcmd
#        with:
#          env: |
#            GITHUB_WORKFLOW: ${{ matrix.base_image }}
#          arch: aarch64
#          distro: none
#          base_image: ${{ matrix.base_image }}
#          githubToken: ${{ github.token }}
#          # Create cached/volume directories on host
#          setup: |
#            mkdir -p ~/.ccache
#
#          # Mount cached directories in the container for faster builds
#          dockerRunArgs: |
#            --volume "${HOME}/.ccache:/root/.ccache" --volume "${PWD}:/repo"
#
#          # Install ccache and gcc/g++ symlinks in the container
#          install: |
#            apt-get update -q -y
#            apt-get install build-essential ccache -q -y
#            /usr/sbin/update-ccache-symlinks
#            echo 'export PATH="/usr/lib/ccache:$PATH"' | tee -a ~/.bashrc
#            pip install cmake auditwheel patchelf wheel
#            echo 'CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)' | tee -a ~/.bashrc
#            mkdir /wheelhouse
#            pip wheel z3-solver==4.12.1.0 -w /wheelhouse -v
#
#          run: |
#            cd /repo
#            cp -R /wheelhouse .
#            z3wheel=$(ls wheelhouse | head -1)
#            auditwheel repair --plat manylinux_2_35_aarch64 wheelhouse/$z3wheel
#
#            pip install -r build-requirements.txt
#            pip install . --no-build-isolation -v -f wheelhouse
#            pip install pytest
#            cd tests && pytest --ignore-glob=*test_nns* --ignore-glob=*test_vulkan* --ignore-glob=*test_gpu* --ignore-glob=*test_openmp* *
